apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: airbyte-minio-storage-claim
  name: airbyte-minio-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi