apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    airbyte: volume-configs
  name: airbyte-volume-configs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi