apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: policy-reporter
spec:
  releaseName: policy-reporter
  chart:
    spec:
      chart: policy-reporter
      sourceRef:
        kind: HelmRepository
        name: policy-reporter
        namespace: flux-system
      version: "2.8.0"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: policy-reporter-values