apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kubeapps
spec:
  releaseName: kubeapps
  chart:
    spec:
      chart: kubeapps
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "8.0.16"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: kubeapps-values