apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dependency-track
spec:
  releaseName: dependency-track
  chart:
    spec:
      chart: dependency-track
      sourceRef:
        kind: HelmRepository
        name: evryfs-oss
        namespace: flux-system
      version: "1.3.5"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: dependency-track-values