apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: litmus
spec:
  releaseName: litmus
  chart:
    spec:
      chart: litmus
      sourceRef:
        kind: HelmRepository
        name: litmuschaos
        namespace: flux-system
      version: "2.7.2"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: litmus-values