apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: campus-registry-secret
  namespace: kyc
spec:
  encryptedData:
    .dockerconfigjson: AgAmYGjV+8er3mWMR8Kl528p5TgwVEM8nEbEjSSeVsdVb/LysSvewNdcd7rffdfy5zZhVZlU9OVbcadPVckGbRZg1haxEoYPNIUz0z5KDcIz0qbFUNqVgJmoWAaWX3JDKyZ2L09Qd53+fDSEBpqj4gkXi1FRijHHsvGiezVpjw8stJW35WTowkf6kwMWNrg6yFsBp9VItFEtSTDhSnl72O6+yFtQhXrynqVrClnBxwZiAZSRPmy602mX7Ir3SXzPR3lbsDp0inbKnKos+7KIv++aPW3TJI07Z6ItluTwR2LnuIBKywF59VcRu7tTWpWZzUtyBPC21Cyb3c/iN7d7cSN/smQaIAU6VoTeeTcE67Q9dVYzY4YguXfBzQw4ufEj4IBNTJiVJwfPwXE6rAcVV8A4S4sIM7fQeeVBgdJGRYsgz5VdGhTUObelED+9S5dcPp8G3+eaBap2UNPnk60sF59FKCj3kvSf5sXeREyja2qjPME9BrO6RFptRCXSXFp9vzDKxPzdlfvpCzA8J1TT8LS2q+AORO8th7oiwYBYRV3yDky22IedZHaLwkaHVrJHW8bjPScMKMcEtkXDUAPzBMRm0XkgXfit+GDaYrXNJ/X5UsKQBna9ZcChqjSsdBFA8HHm/qnnDrF27q35Ufwm7tnYG9K2sDj2P+NgPH9AZtH51rgKcwAfZOalTEs5T5W3RugOmqNPT//Ay2a5kCqK13BPDtlGLB6fpZR7G9P7q1xbn36/KifYUKKpEKGLCXbQ+OCqxa3LRoQV2Npy5POZQo2TxgDP5TPYClr3Y82zPGqUxcaa73dpwvbLRx4XDVCLBLp/JFs7dBWNbB//Vi6acka88bNyv2FxKH+ahxopwkab0MpdPsNa81udFDzq3WU/KnLBJ5U5RaoT5iMavJFjb2jtxr+qJ8fhe4PzY5MCBwNZikEN+PI2xHU=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: campus-registry-secret
      namespace: kyc
    type: kubernetes.io/dockerconfigjson

