apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: actions-runner-system
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: actions-runner-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml