apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: actions-runner-system
spec:
  releaseName: actions-runner-system
  chart:
    spec:
      chart: actions-runner-controller
      sourceRef:
        kind: HelmRepository
        name: github-actions
        namespace: flux-system
      version: "0.18.0"
  interval: 10m0s
  install:
    remediation:
      retries: 10
  valuesFrom:
    - kind: ConfigMap
      name: actions-runner-values