apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redmine
spec:
  releaseName: redmine
  chart:
    spec:
      chart: redmine
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "20.3.3"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: redmine-values