apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: deploy-yakeey-core
  namespace: yakeey
spec:
  providerRef:
    name: slack
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: 'yk-gitops'
    - kind: Kustomization
      name: '*'