#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kyverno
#  namespace: flux-system
#spec:
#  interval: 10m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno
#  prune: true
#  wait: true
#  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kyverno-policies
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kyverno
#  interval: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno-policies
#  prune: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: helm-repositories
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nemo-demo-flux2-sync
  path: ./infrastructure/sources
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: sonar
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nemo-demo-flux2-sync
  path: ./infrastructure/sonar
  prune: true
  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: vault
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nemo-demo-flux2-sync
  path: ./infrastructure/vault
  prune: true
  validation: client
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: kubeapps
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kubeapps
#  prune: true
#  validation: client
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: confluent-operator
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/confluent-operator
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: kafka-plateform
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kafka
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: airbyte
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/airbyte/overlays/stable
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: loki
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/logging/loki
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: policy-reporter
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kyverno-reporter
#  prune: true
#  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: harbor
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nemo-demo-flux2-sync
  path: ./infrastructure/harbor
  prune: true
  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: milvus
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/milvus
#  prune: true
#  validation: client
---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: nemo-demo-flux2-sync
  path: ./infrastructure/keycloak
  prune: true
  validation: client