#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kyverno
#  namespace: flux-system
#spec:
#  interval: 10m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno
#  prune: true
#  wait: true
#  timeout: 5m
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
#kind: Kustomization
#metadata:
#  name: kyverno-policies
#  namespace: flux-system
#spec:
#  dependsOn:
#    - name: kyverno
#  interval: 5m
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  serviceAccountName: kustomize-controller
#  path: ./infrastructure/kyverno-policies
#  prune: true
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: helm-repositories
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/sources
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: sonar
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/sonar
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: cert-manager
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/cert-manager
#   prune: true
#   validation: client
#   postBuild:
#     substituteFrom:
#       - kind: ConfigMap
#         name: cert-manager-version
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: certs
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/certs
#   prune: true
#   validation: client
apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: keycloak
  namespace: flux-system
spec:
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./infrastructure/keycloak
  prune: true
  validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: sealed-secrets
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/sealed-secrets
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: vault
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/vault
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: secrets
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/secrets
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: github-actions
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/github-actions
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: github-actions-runner
#   namespace: flux-system
# spec:
#   interval: 1m
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/github-actions-runner
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: chatops
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/chatops
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: chatops-yakeey
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/chatops-yakeey
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: litmus
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/litmus
#   prune: true
#   validation: client
# ---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: kubeapps
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kubeapps
#  prune: true
#  validation: client
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: confluent-operator
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/confluent-operator
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: kafka-plateform
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kafka
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: airbyte
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/airbyte/overlays/stable
#  prune: true
#  validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: loki
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/logging/loki
#  prune: true
#  validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: dependency-track
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/dependency-track
#   prune: true
#   validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: policy-reporter
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/kyverno-reporter
#  prune: true
#  validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: harbor
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/harbor
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: faros
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/faros
#   prune: true
#   validation: client
# ---
# apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
# kind: Kustomization
# metadata:
#   name: milvus-operator
#   namespace: flux-system
# spec:
#   interval: 10m0s
#   sourceRef:
#     kind: GitRepository
#     name: flux-system
#   path: ./infrastructure/operators/milvus
#   prune: true
#   validation: client
#---
#apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
#kind: Kustomization
#metadata:
#  name: milvus
#  namespace: flux-system
#spec:
#  interval: 10m0s
#  sourceRef:
#    kind: GitRepository
#    name: flux-system
#  path: ./infrastructure/milvus
#  prune: true
#  validation: client
