apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: verify-git-repositories
  annotations:
    pod-policies.kyverno.io/autogen-controllers: none
    policies.kyverno.io/title: Control Git Repository
    policies.kyverno.io/category: Gitops
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Gitops Workload git repository must be verified provenance .
spec:
  # This provides users a working example of how an admin
  # would be able to enforce git repository sources across
  # all tenants.
  validationFailureAction: audit # Change to 'enforce' once the specific org url is set.
  rules:
    - name: github-repositories-only
      exclude:
        resources:
          namespaces:
            - flux-system
      match:
        resources:
          kinds:
            - GitRepository
      validate:
        message: ".spec.url must be from a repository within the organisation Octo Campus"
        anyPattern:
          - spec:
              url: "https://github.com/octocampus/?*"
          - spec:
              url: "ssh://git@github.com/octocampus/?*"
          - spec:
              url: "https://github.com/yakeey/?*"
          - spec:
              url: "ssh://git@github.com/yakeey/?*"