apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: milvus
resources:
  - namespace.yaml
  - release.yaml
configMapGenerator:
  - name: milvus-operator-values
    files:
      - values.yaml=values.yaml
configurations:
  - kustomizeconfig.yaml