apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: milvus-operator
spec:
  releaseName: milvus-operator
  chart:
    spec:
      chart: milvus-operator
      sourceRef:
        kind: HelmRepository
        name: milvus-operator
        namespace: flux-system
      version: "0.7.7"
  interval: 10m0s
  install:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: milvus-operator-values