apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: accelerate
spec:
  encryptedData:
    address: AgC1cWdgZZ2+L1Ye8W8jI10T5aFrVCzB0QcIC98Hxs2uitR0pWkGOIOzKJ/Pd+wUN+BpzhwIuNlaO3TTg2z6U18AdzNzjao5sEc33oBh/UBgfnob/0vklYT+ZSphElEyfXUlD/x++/bR1w93BHOT5nTY2fNWwoOxJ4O443Txey09XukboCULB+qXhybU4wksIetLyVU8LrNl4kTZ98PFxAK1tepJjZzPVErxh40575OL6d3K5+WWy+oT4+fSbN7VIBYMhU72uE8daMhfeyRgUal2geOAGKqUP/q0rfILtasA17TgkBEDz/Oo+oX9A82N4E/EKFbGAimuc3mvqykgNAq+7v3r/jMe+3ysZHR1cyhTCCA5oJu+tPfZHgieaGsKnQRjproX8xmr7wwUSEqRZMGhr4Vb1IhVhLeMfcoNSC6shdjDe5gHquO7B+QMf2ual7OnuaKqj3Srzp5x8D2BY/ddFblOGVliAjjcoewjY5W7ldq1XTw1KxPSN2e4EZFAOtvBbyF1HQQwNSVdmxV/Ya3FvTn87GIsvyxWUFl6GLz1h9TFFpJ6UOIH1wzkiW0HQ1uUC7EYLIkoVBL7nGnak6ApU4xmUWbO8yFrDvZGYs9Z4YPLZLUwZgGQKpZep2QL9Iw0yABPjQec4WKV/UMOnp8ijNDm/42N53i445YlYVfh4GHqs7GCOLElsaaxSKPFjiys+LrXHwR0J6Zpwo9B5cAqrE3K521LfC0DsiZ48OwwNAGdlpcQRHTsv/YyKJaDtYgcZZ4pe5KLXz7aO0cDsU47GqbUq7HH0ZvyljwfgqkDcVWVQ+pO0v92bLuvqn1wUA4bl77fXdqRUpdFeGxJ+MxJb7HgZnO/u+U=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: accelerate
    type: Opaque

