apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: discord-url
  namespace: flux-system
spec:
  encryptedData:
    address: AgApDbzYPcnkCqiIF4/A0EGjyJ+9e/QE8qV0gP+UwL8Hx0oe+W5stzdakcQi+wo4ZjHhxiTNaDg/M4wpWRvvBAmq/oL9VzqBG91lc4jxKalnM3bP4vcCyJiyntiER+Br9Ufx7HI6SSE0QLC5U9bP7kMoJ8/MLxo6BI04gPMgfZJQYsIHzveeeoPH5z2JH3DqV5LqWZigzrIy5RugEzl/i3KPJcwXK8+miqzeA98kgtFfBkIWx2n6TCChxwm44gCV2v1U211MJuintNFfFju7o8+n6G08cpY7ha+5kitOHxNpTycHbaIdTuBv4Ndvs0LhitvWQ4tZ+cJtbY4IsNQBYToOwvJxkY2Tkfhn6w4UrhUBw+7MFqlOuzmC2fPwI5BSBN4TAFVPWNEmbN5wRAam2fKRJKQL2wyidBu7fysQ6YqPq4be2OwsJDzngDgPyr7SK0DHtUj0dwZ7VLB9KvFJMJUuGy8juPKuaawKMCmQzaIx1WmBuuEJ4/WP/szPEciAVLap35UqIWZDExNEt6VgN7US7jrOoWmSAcNJ9kWM2TfRs3HJOTBSR/ALvEdT4SmghYo3jy7ap9pTz23OX0rTRexoHQ1DwKS+M2JUF3ZCwDGTVekKNXn170rgfp80P9z2E9ic6GChiWIR5VtHtKHwgLxQ3skbt+Rm7kO1tGWU7doGcUu/z5FXb+GrryOabO/o4BhGPOuLGYnI8nxeIvMBXurKpAs1t0Ersa57SYyjtk1fEFUyd8f9LfsHp9EQ5fiNBnWOdnq3MOoaBtsnnFwQ3+dYfMM08x/Q5ZvvlL0bpdq+RvJAnAbIQ8JY3IeCPN0HU/RSl9BjryB16Tuo3ujmALDBZXnyhSVu8Q0=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: discord-url
      namespace: flux-system
    type: Opaque

